#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int fullpower = 127;
float decimalNumber = 0.007;
bool onFleek = true;
string intro = "Hello my name is mark!";

// Functions
/motor[rightMotor] = vexRT[Ch1];
void moveforward(){
	startMotor(leftMotor, fullpower);   // start left moter
	startMotor(rightMotor, fullpower);  // start right motor
}

void stopDriveMotors(){
	stopMotor(leftMotor);								// stop left motor
	stopMotor(rightMotor);							// stop right motor
}

void rightSwingTurns(){
	startMotor( leftMotor, fullpower/2); // right swing turn
	wait(1.85);														// runs for 3 seconds
	stopMotor(leftMotor);					// stops left motor
}

void leftSwingTurns(){
	startMotor(rightMotor, fullpower/2); // left swing turn
	wait(1.85);														// runs for 3 seconds
	stopMotor(rightMotor);					// stops right motor
}

void rightGentleTurn(){
	startMotor(leftMotor, fullpower/2); // right swing turn
	startMotor(rightMotor, fullpower/6);
	wait(1.85);														// runs for 3 seconds
	stopMotor(leftMotor);					// stops left motor
}
task main()
{
	moveforward();
	wait(3);                    				// run motor for 3 seconds
	stopDriveMotors();
	wait(3);
	rightSwingTurns();
	wait(4);
	moveforward();
	wait(2);
	stopDriveMotors();
	wait(2);
	rightGentleTurn();
	wait(3);
	stopDriveMotors();
	wait(3);
	leftSwingTurns();
	wait(3);
	stopDriveMotors();
	wait(5);

	startMotor(rightMotor, fullpower/2); // left swing turn
	wait(1.85);														// runs for 3 seconds
	stopMotor(rightMotor); 							// stops right motor
	wait(2);

	// Point turn

	startMotor(leftMotor, fullpower/2); // start right point turn
	startMotor(rightMotor, -fullpower/2);// start right motor
	wait(.9);															// wait
	stopMotor(leftMotor); 							 // stops left motor
	stopMotor(rightMotor);								// stops right motor
	wait(1);

	startMotor(leftMotor, -fullpower/2);  // start left  point turn
	startMotor(rightMotor, fullpower/2); // start right motor
	wait(.9);
	stopMotor(leftMotor);								// stops leftMotor
	stopMotor(rightMotor);							// stops rightMotor
	wait(1);



}
